name: Generate File Paths

on:
  push:
jobs:
  generate_file_paths:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate file paths and write to txt file
      run: python generate_file_paths.py
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add file_paths.txt
        git commit -m "Update file_paths.txt"
        git push
